# ── Keyword-based objection fallback ─────────────────────────────────────
# When Claude fails to return triggered=true, this lookup provides the
# approved rebuttal so the rep ALWAYS sees objection coaching.
#
# "stages" field (optional): if present, the objection only fires when the
# current call stage is in this list. Omit for objections valid in any stage.
OBJECTION_REBUTTALS = {
    # ── Personal info resistance (checked FIRST — more specific than price_inquiry) ──
    "personal_info": {
        "signals": [
            "don't want to give my", "why do you need my information",
            "why do you need my name", "why do you need my number",
            "don't give out my", "not comfortable giving",
            "rather not give my", "not giving you my",
            "do you really need my information",
            "do you really need to ask my information",
            "don't need my information", "why do you need that information",
        ],
        "type": "Personal Info Resistance",
        "summary": "Customer doesn't want to share personal information yet",
        "suggestions": [{"label": "Personal Info Rebuttal", "text": "I totally understand being careful with your information. How about this \u2014 let me walk you through the equipment and pricing first so you can see if it's the right fit, and then we can get your information once you're ready to move forward."}],
        "transitions": ["Does that work for you?", "Should we look at the equipment first?"],
    },
    # ── Price inquiry (early call — customer asking about price, NOT reacting to one) ──
    "price_inquiry": {
        "signals": [
            "just wanted to know the price", "just want to know the price",
            "just wanted the price", "just want the price",
            "wanted to know the prices", "want to know the prices",
            "wanted to know the total", "want to know the total",
            "just the price", "tell me the price", "give me the price",
            "just give me the price", "skip to the price", "get to the price",
            "just want the price first", "wanted to know the price first",
            "what are the prices", "what are your prices", "what are your offers",
            "how much does it cost", "how much is it", "how much is everything",
            "what's the total", "what is the total",
        ],
        "stages": ["intro", "discovery", "collect_info"],
        "type": "Wants Pricing First",
        "summary": "Customer wants to skip ahead to pricing",
        "suggestions": [{"label": "Redirect to Discovery", "text": "Absolutely, I'll get you the pricing! To give you an accurate quote, I just need to know what equipment you'll need for your home. Let me ask you a couple quick questions so I can build out the right system and get you the best price \u2014 it'll only take a minute."}],
        "transitions": ["What has you looking into security?", "Have you ever had a security system before?"],
    },
    # ── Price objection (after price has been quoted — sticker shock) ──
    "price_general": {
        "signals": [
            "too expensive", "too much money", "that's a lot", "can't afford",
            "costs a lot", "pricey", "cost too much", "lot of money",
            "that's expensive", "kind of expensive", "kinda expensive",
            "pretty expensive", "really expensive", "so expensive",
            "why do i have to pay", "why am i paying", "why is it",
            "i thought it was free", "thought the equipment was free",
            "are for free", "said it was free", "was supposed to be free",
            "that's more than", "more than i expected", "wasn't expecting",
            "didn't expect to pay", "didn't think i'd have to pay",
            "what am i paying", "what do i pay", "what would i pay",
            # Short signals (unambiguous in closing context)
            "expensive", "it's expensive", "that's too much", "too much",
            "how much should it cost", "how much will it cost",
            "how much does that cost", "what does it cost",
            "what can you do about it", "can you do something about",
            "can you lower", "can you bring it down", "any discounts",
            "is there a discount", "give me a discount", "lower the price",
            "that's a lot of money", "way too much",
        ],
        "stages": ["build_system", "closing"],
        "type": "Price / General Expense",
        "summary": "Customer is concerned about the price",
        "suggestions": [{"label": "Price Rebuttal", "text": "I understand where you're coming from; it can definitely seem like a lot at first. Just to clarify, are you referring to the upfront equipment cost or the monthly monitoring fee?"}],
        "transitions": ["Does that make sense?", "Would you like to try it for the 60-day trial?"],
    },
    "upfront_cost": {
        "signals": [
            "upfront cost", "up front cost", "equipment cost", "pay that much today",
            "that much upfront", "that much up front", "down payment",
            "pay for the equipment", "pay for equipment",
            "why do i have to pay for the equipment", "that much for equipment",
            "pay all that", "pay that today",
            "that's a lot for equipment", "a lot just for equipment",
        ],
        "stages": ["closing"],
        "type": "Upfront Cost",
        "summary": "Customer thinks the upfront equipment cost is too high",
        "suggestions": [{"label": "Upfront Cost Rebuttal", "text": "I hear you, upfront costs can feel like a lot. Keep in mind, this covers everything you need: the equipment, app access, account setup, and more. Let me ask, what price were you hoping for? Maybe we can find a way to meet you halfway and make this work for you."}],
        "transitions": ["What price were you hoping for?", "Would the 60-day trial help?"],
    },
    "monthly_bill": {
        "signals": [
            "monthly fee is", "per month is too", "a month is too", "monthly cost",
            "monthly is too", "monthly is a lot", "thirty three a month",
            "thirty two a month",
            "a month for monitoring", "month just for monitoring",
            "every month on top", "monthly on top of", "plus a monthly",
            "and then monthly", "monthly too", "pay every month too",
        ],
        "stages": ["closing"],
        "type": "Monthly Bill",
        "summary": "Customer thinks the monthly monitoring fee is too much",
        "suggestions": [{"label": "Monthly Fee Rebuttal", "text": "I hear you; the monthly monitoring fee is $32.99. Honestly, that's one of the most affordable rates on the market, especially considering all the equipment included in your system. That's basically just about a dollar a day for full protection for your family. It's peace of mind that's hard to put a price on."}],
        "transitions": ["Does that sound reasonable?", "Would you like to try it for the 60-day trial?"],
    },
    "spouse": {
        "signals": [
            "talk to my wife", "talk to my husband", "ask my wife", "ask my husband",
            "check with my wife", "check with my husband", "talk to my partner",
            "run it by my", "discuss with my", "talk to my spouse",
            "my wife needs to", "my husband needs to",
            "let me ask my wife", "let me ask my husband",
            "without my wife", "without my husband",
            "wife is not here", "husband is not here",
            "need my wife", "need my husband",
        ],
        "stages": ["build_system", "closing"],
        "type": "Spouse",
        "summary": "Customer wants to talk to their partner first",
        "suggestions": [{"label": "Spouse Rebuttal", "text": "Sure, I completely understand, I'd want to check with my partner too before making a big decision like this. Just a heads up, the discount ends tonight, and I wouldn't want you to miss out. But don't worry, we have a 60-day return policy with a full refund, so you can try it and see if this system is the right fit for your needs."}],
        "transitions": ["Does that sound fair?", "Would the 60-day trial help with that decision?"],
    },
    "no_urgency": {
        "signals": [
            "call you back", "think about it", "let me think", "need to think",
            "want to think", "sleep on it", "not ready yet", "not sure yet",
            "give me some time", "come back later", "i'll get back",
            "get back to you", "call back later", "maybe later",
            "not right now", "not today",
            "i'll call back", "call back tomorrow", "call back another",
            "need some time", "give me a day", "give me a few days",
            "think it over", "think on it", "sit on it",
            "need to do more research",
        ],
        "stages": ["build_system", "closing"],
        "type": "No Urgency",
        "summary": "Customer wants to think about it or call back later",
        "suggestions": [{"label": "No Urgency Rebuttal", "text": "No worries, you can definitely call us back when the time comes. Just keep in mind, the discount ends tonight, and I wouldn't want you to miss out. Is there anything else you'd like to know to help make your decision?"}],
        "transitions": ["Is there anything else I can help clarify?", "Would the 60-day trial help?"],
    },
    "shopping_around": {
        "signals": [
            "shopping around", "other companies", "calling other",
            "few different companies", "do some research", "do my research",
            "due diligence", "other options", "other quotes",
            "send me a quote", "send over a quote", "looking at other",
            "hear them out", "compare prices", "comparing",
            "look at other", "checking out other",
            "looking at adt", "looking at ring",
            "looking at simplisafe", "looking at vivint",
            "what about adt", "what about ring", "what about simplisafe",
        ],
        "stages": ["build_system", "closing"],
        "type": "Shopping Around",
        "summary": "Customer wants to compare with other companies",
        "suggestions": [{"label": "Shopping Around Rebuttal", "text": "I totally understand \u2014 it's smart to compare. Just so you know, a lot of people compare us with the big names and end up choosing Cove because of the no-contract, the pricing, and the customer service. And with the 60-day trial, you can try it risk-free. If it's not the right fit, you send it back for a full refund."}],
        "transitions": ["Does that make sense?", "Would you like to go ahead and try it risk-free?"],
    },
    "needs": {
        "signals": [
            "not sure i need", "don't think i need", "do i really need",
            "is it worth", "don't know if i need", "not convinced",
            "don't really need",
            "do i need all this", "do i need all that",
            "is all that necessary", "do i need that many",
            "more than i need", "i don't need all",
        ],
        "stages": ["build_system", "closing"],
        "type": "Needs",
        "summary": "Customer isn't sure they need the system",
        "suggestions": [{"label": "Needs Rebuttal", "text": "No worries! We have a 60-day return policy with a full refund, so you can try it and see if this system is the right fit for your needs."}],
        "transitions": ["Would you like to try it risk-free?", "Does that sound fair?"],
    },
    "technician": {
        "signals": [
            "can someone install", "send someone to install",
            "need a technician", "want a technician", "get a technician",
            "get the technician", "wanted to get the technician",
            "professional install", "hard to set up", "too hard to install",
            "someone come out", "send somebody", "come set it up",
            "i'm not good with technology", "not tech savvy",
            "not a techy", "not techy", "i'm not techy",
            "technician come out", "have a technician",
            "technician that can come", "technician to come",
            "can't install", "don't know how to install",
            "someone to set it up", "someone to install",
            # Natural phrasing from real calls
            "install for me", "install it for me", "install everything",
            "do you have installation", "is there installation",
            "someone who can install", "who's going to install",
            "don't want self install", "don't want to install",
            "i don't want to install it myself",
            "self installation", "not comfortable installing",
        ],
        "stages": ["build_system", "closing"],
        "type": "Technician / DIY",
        "summary": "Customer wants professional installation",
        "suggestions": [{"label": "DIY Rebuttal", "text": "Great question! Our equipment is really easy to install \u2014 it's all wireless, so there's no drilling. Most customers set it up in about 20 minutes. But if you'd prefer, we do have a third-party technician service starting at $129. Our customer service team can also walk you through setup step by step over the phone."}],
        "transitions": ["Does that sound doable?", "Would you like to give DIY a try first?"],
    },
    "no_monitoring": {
        "signals": [
            "self monitor", "self-monitor", "don't want monitoring",
            "no monitoring", "monitor myself", "don't need monitoring",
            "without monitoring", "no monthly", "don't want a monthly",
            "don't want the monthly", "not want a monthly",
            "i'll monitor it myself", "monitor it myself",
            "do i have to have monitoring", "is monitoring required",
            "is it possible to not have monitoring",
            "is it possible to not have a monthly",
            "without the monthly", "skip the monitoring",
            "a monitoring is it possible", "monitoring is it possible",
            "can i not have monitoring", "do i need monitoring",
            "is the monitoring mandatory", "monitoring optional",
        ],
        "stages": ["build_system", "closing"],
        "type": "Doesn't Want Monitoring",
        "summary": "Customer doesn't want professional monitoring",
        "suggestions": [{"label": "Monitoring Rebuttal", "text": "At Cove, we don't offer self-monitoring because we want to make sure our customers are fully protected 24/7, with police, fire, and medical support included. The monthly monitoring fee is just $32.99, about a dollar a day, for complete peace of mind that keeps your family safe without compromise."}],
        "transitions": ["Does that make sense?", "Would you like to try it for 60 days?"],
    },
    "only_cameras": {
        "signals": [
            "just want cameras", "only want cameras", "just the cameras",
            "only need cameras", "cameras only", "just cameras",
            "only interested in cameras", "just need cameras",
            "don't need sensors", "don't need the sensors",
            "don't want sensors",
        ],
        "stages": ["build_system", "closing"],
        "type": "Only Wants Cameras",
        "summary": "Customer only wants cameras without the full system",
        "suggestions": [{"label": "Cameras Only Rebuttal", "text": "I understand where you're coming from. Cameras are great for keeping an eye on your home, but with our full system, including sensors, you get 24/7 protection with police, fire, and medical response, even when you're not watching. The sensors are what trigger the alarm and dispatch help automatically."}],
        "transitions": ["Does that make sense?", "Would you like the full protection?"],
    },
    "payment_declined": {
        "signals": [
            "card declined", "card didn't work", "payment failed", "won't go through",
            "didn't go through", "card not working", "card was declined",
            "not going through", "keeps declining", "says declined",
            "error with my card", "card isn't working",
        ],
        "stages": ["closing"],
        "type": "Payment Declined",
        "summary": "Customer's payment method was declined",
        "suggestions": [{"label": "Payment Rebuttal", "text": "Oh no problem \u2014 we accept any standard Visa, Mastercard, or Discover credit or debit card. Unfortunately we can't accept prepaid cards, Cash App cards, or PayPal. Do you have another card you could use?"}],
        "transitions": ["Do you have another card?", "Would you like to try a different payment method?"],
    },
    "existing_system": {
        "signals": [
            "already have a system", "use my existing", "keep my current",
            "already have equipment", "use the equipment i have",
            "already have cameras", "already have sensors", "already installed",
            "keep what i have", "use what i have",
        ],
        "type": "Existing System",
        "summary": "Customer wants to use their existing security equipment",
        "suggestions": [{"label": "Existing System Rebuttal", "text": "Great news \u2014 you can actually keep using the equipment that's already installed there. What we'll do is set you up with a new account, get you a new hub and panel, and then we'll reset the existing cameras and sensors to connect to your new account."}],
        "transitions": ["Does that make sense?", "Should we get that set up for you?"],
    },
    "autopay": {
        "signals": [
            "when do i get charged", "billing date", "when is the payment",
            "autopay", "auto pay", "when does it charge", "first payment",
            "when do they charge", "when does billing start",
            "when is the first charge", "what day do i pay",
        ],
        "stages": ["closing"],
        "type": "Autopay / Billing",
        "summary": "Customer has questions about billing date or autopay",
        "suggestions": [{"label": "Autopay Rebuttal", "text": "The autopay runs on the 5th of each month by default, but if you need a different billing date, you can call our customer service team after setup and they'll adjust it for you. Today you just pay for the equipment, and the monthly monitoring starts after your first month."}],
        "transitions": ["Does that work for you?", "Should we go ahead and get you set up?"],
    },
}
